### PR TITLE
Update egui and windows (again)

### PR DESCRIPTION
**Pull request by Cubesicle**
Updated egui to v0.25 and windows to v0.52. I also fixed some stuff.

### CODE REVIEW

**Comment by mfloob** [comment]
Thank you.

**Comment by mfloob** [comment]
Gotta fix these conflicts sometime.

**Comment by Cubesicle** [comment]
Done

**Comment by mfloob** [comment]
> Done

I meant I was going to fix them but thanks again lol.

**Comment by Cubesicle** [comment]
Lol no problem.

**Pull request merged**
